### ISSUE TITLE
minitest/mock now depends on minitest/stub (but doesn't declare requirement)

### ISSUE THREAD

**Issue by geemus** [minitest/minitest#1022]
In our test suite we require `minitest` and `minitest/mock`. When trying to update to the latest, that broke for us at require time for `minitest/mock` like this:

```
/home/runner/_work/anchor/anchor/vendor/bundle/ruby/3.2.0/gems/minitest-5.25.3/lib/minitest/mock.rb:269:in `<module:Expectations>': undefined method `infect_an_assertion' for Minitest::Expectations:Module (NoMethodError)

  infect_an_assertion :assert_mock, :must_verify, :unary
  ^^^^^^^^^^^^^^^^^^^
	from /home/runner/_work/anchor/anchor/vendor/bundle/ruby/3.2.0/gems/minitest-5.25.3/lib/minitest/mock.rb:261:in `<main>'
	from /home/runner/_work/anchor/anchor/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /home/runner/_work/anchor/anchor/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /home/runner/_work/anchor/anchor/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
	from /home/runner/_work/anchor/anchor/test/test_helper.rb:6:in `<main>'
	from /home/runner/_work/anchor/anchor/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /home/runner/_work/anchor/anchor/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /home/runner/_work/anchor/anchor/test/controllers/api/v0/acme/eab_tokens_controller_test.rb:3:in `<main>'
	from /home/runner/_work/anchor/anchor/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /home/runner/_work/anchor/anchor/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /home/runner/_work/anchor/anchor/vendor/bundle/ruby/3.2.0/gems/railties-7.1.4.1/lib/rails/test_unit/runner.rb:51:in `block in load_tests'
	from /home/runner/_work/anchor/anchor/vendor/bundle/ruby/3.2.0/gems/railties-7.1.4.1/lib/rails/test_unit/runner.rb:51:in `each'
	from /home/runner/_work/anchor/anchor/vendor/bundle/ruby/3.2.0/gems/railties-7.1.4.1/lib/rails/test_unit/runner.rb:51:in `load_tests'
	from /home/runner/_work/anchor/anchor/vendor/bundle/ruby/3.2.0/gems/railties-7.1.4.1/lib/rails/test_unit/runner.rb:43:in `run'
	from /home/runner/_work/anchor/anchor/vendor/bundle/ruby/3.2.0/gems/railties-7.1.4.1/lib/rails/commands/test/test_command.rb:33:in `perform'
	from /home/runner/_work/anchor/anchor/vendor/bundle/ruby/3.2.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
	from /home/runner/_work/anchor/anchor/vendor/bundle/ruby/3.2.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/runner/_work/anchor/anchor/vendor/bundle/ruby/3.2.0/gems/railties-7.1.4.1/lib/rails/command/base.rb:178:in `invoke_command'
	from /home/runner/_work/anchor/anchor/vendor/bundle/ruby/3.2.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
	from /home/runner/_work/anchor/anchor/vendor/bundle/ruby/3.2.0/gems/railties-7.1.4.1/lib/rails/command/base.rb:73:in `perform'
	from /home/runner/_work/anchor/anchor/vendor/bundle/ruby/3.2.0/gems/railties-7.1.4.1/lib/rails/command.rb:71:in `block in invoke'
	from /home/runner/_work/anchor/anchor/vendor/bundle/ruby/3.2.0/gems/railties-7.1.4.1/lib/rails/command.rb:149:in `with_argv'
	from /home/runner/_work/anchor/anchor/vendor/bundle/ruby/3.2.0/gems/railties-7.1.4.1/lib/rails/command.rb:69:in `invoke'
	from /home/runner/_work/anchor/anchor/vendor/bundle/ruby/3.2.0/gems/railties-7.1.4.1/lib/rails/commands.rb:18:in `<main>'
	from /home/runner/_work/anchor/anchor/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /home/runner/_work/anchor/anchor/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from ./bin/rails:4:in `<main>'
```

It looks like last week the usage of `infect_an_assertion` was added to mock: https://github.com/minitest/minitest/commit/2d542ffa8045d40fed7fae733c6ab674a2ffbf09#diff-2a72d0121a0eb22e9f32a1ce654e5132391273007bf643b5ae68fbbc2800dea4R269

That appears to be defined here: https://github.com/minitest/minitest/blob/master/lib/minitest/spec.rb#L4

Maybe that definition should be moved to a neutral place and then required from bath spec and mock now? For now I solved this for myself in the same way autorun would solve it, which is to say I require spec prior to mock. Since I don't otherwise need spec I'd prefer not to do that though, and it also feels brittle to have that ordered require needed.

Happy to work on a fix, but wanted to lay it out and get some guidance on if there was interest and how to proceed. Thanks!

**Comment by zenspider** [comment]
So to clarify, you're requiring minitest + minitest/mock but NOT minitest/autorun? 

Curious: Any reason why? How are you kicking off the tests?

**Comment by zenspider** [comment]
This is fixed and will be released shortly.

**Comment by zenspider** [comment]
Released 5.25.4

**Comment by geemus** [comment]
@zenspider Thanks for the quick fix. I suspected it was partly self-inflicted pain given our usage, but it still seemed like a good thing to fix just in case (and shouldn't really hurt anything).

Yeah, we were requiring minitest (via bundler/gemfile I believe) and then mock is required in our test_helper. I'm not exactly sure why to be honest, it was that way when I got here. It's part of a rails app, so we generally use `bin/rails test ...` to kick things off. I'm not sure if that relates to how rails generated things at the time the app was created or if it was something that was changed at some point along the line. I can try to dig deeper if it matters, but given that this is now fixed it seems probably not that important of a detail to dig up.
