### ISSUE TITLE
v5.16.0 with `ci_queue` with test_order random|parallel throws TypeError

### ISSUE THREAD

**Issue by serioushaircut** [minitest/minitest#913]
Hello,

on upgrading from 5.15 to 5.16 we noticed a TypeError because `Minitest.seed` is nil here:
https://github.com/minitest/minitest/blob/v5.16.0/lib/minitest/test.rb#L70
```
    def self.runnable_methods
      methods = methods_matching(/^test_/)

      case self.test_order
      when :random, :parallel then
        srand Minitest.seed                   # <-- Here
        methods.sort.shuffle
      when :alpha, :sorted then
        methods.sort
      else
        raise "Unknown test_order: #{self.test_order.inspect}"
      end
    end
```

This code path is apparently not entered in every case, but for `test_order = parallel` with ci_queue underneath it is.

We didn't change anything else, this upgrade test was run in isolation.

For completeness, our command and the resulting stacktace:
```
✗1 ~/debug-minitest-5.16.0 % bundle exec minitest-queue run --max-requeues 1 --requeue-tolerance 0.01 --timeout 45 --seed 123456 --queue redis://localhost:18962/0 -Itest test/my_test.rb
The retry queue does not contain any failure, we'll process the main queue instead.
bundler: failed to load command: minitest-queue (~/.bundle/banking/bin/minitest-queue)

~/.bundle/.../gems/minitest-5.16.0/lib/minitest/test.rb:70:in `srand': no implicit conversion of nil into Integer (TypeError)
        from /home/spin/.bundle/banking/gems/minitest-5.16.0/lib/minitest/test.rb:70:in `runnable_methods'
        from /home/spin/.bundle/banking/gems/ci-queue-0.22.1/lib/minitest/queue.rb:205:in `block in loaded_tests'
        from /home/spin/.bundle/banking/gems/ci-queue-0.22.1/lib/minitest/queue.rb:204:in `each'
        from /home/spin/.bundle/banking/gems/ci-queue-0.22.1/lib/minitest/queue.rb:204:in `flat_map'
        from /home/spin/.bundle/banking/gems/ci-queue-0.22.1/lib/minitest/queue.rb:204:in `loaded_tests'
        from /home/spin/.bundle/banking/gems/ci-queue-0.22.1/lib/minitest/queue/runner.rb:274:in `populate_queue'
        from /home/spin/.bundle/banking/gems/ci-queue-0.22.1/lib/minitest/queue/runner.rb:79:in `run_command'
        from /home/spin/.bundle/banking/gems/ci-queue-0.22.1/lib/minitest/queue/runner.rb:35:in `public_send'
        from /home/spin/.bundle/banking/gems/ci-queue-0.22.1/lib/minitest/queue/runner.rb:35:in `run!'
        from /home/spin/.bundle/banking/gems/ci-queue-0.22.1/lib/minitest/queue/runner.rb:19:in `invoke'
        from /home/spin/.bundle/banking/gems/ci-queue-0.22.1/exe/minitest-queue:5:in `<top (required)>'
        from /home/spin/.bundle/banking/bin/minitest-queue:25:in `load'
        from /home/spin/.bundle/banking/bin/minitest-queue:25:in `<top (required)>'
```

**Comment by serioushaircut** [comment]
Mmh, I'm uncertain 
whether "ci-queue domain" is now supposed to call this new cattr_accessor `:seed` on `Minitest` 
or 
whether "minitest domain" has to make sure that it itself reads the `ordering_seed` from "ci-queue" from anywhere [here where it is used and changed](https://github.com/Shopify/ci-queue/blob/master/ruby/lib/minitest/queue/runner.rb#L516) or maybe here from the [configuration ](https://github.com/Shopify/ci-queue/blob/504db35d235d3c1d77c95050737bec8c12c56d6d/ruby/lib/ci/queue/configuration.rb#L18)?
