### ISSUE TITLE
TypeError when certain tests fail (since 5.16.0)

### ISSUE THREAD

**Issue by irphilli** [minitest/minitest#916]
Hi!

I'm using minitest, along with capybara and selenium-webdriver.

I've noticed that since updating to 5.16.0, for _some_ tests that fail, I'll get something like this in the output:
```
/Users/phil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/minitest-5.16.1/lib/minitest/test.rb:225:in `dump': no _dump_data is defined for class Binding (TypeError)
	from /Users/phil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/minitest-5.16.1/lib/minitest/test.rb:225:in `new_exception'
	from /Users/phil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/minitest-5.16.1/lib/minitest/test.rb:219:in `rescue in neuter_exception'
	from /Users/phil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/minitest-5.16.1/lib/minitest/test.rb:211:in `neuter_exception'
	from /Users/phil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/minitest-5.16.1/lib/minitest/test.rb:208:in `rescue in sanitize_exception'
	from /Users/phil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/minitest-5.16.1/lib/minitest/test.rb:204:in `sanitize_exception'
	from /Users/phil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/minitest-5.16.1/lib/minitest/test.rb:201:in `rescue in capture_exceptions'
	from /Users/phil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/minitest-5.16.1/lib/minitest/test.rb:194:in `capture_exceptions'
	from /Users/phil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/minitest-5.16.1/lib/minitest/test.rb:95:in `block (2 levels) in run'
	from /Users/phil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/minitest-5.16.1/lib/minitest.rb:296:in `time_it'
	from /Users/phil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/minitest-5.16.1/lib/minitest/test.rb:94:in `block in run'
	from /Users/phil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/minitest-5.16.1/lib/minitest.rb:391:in `on_signal'
	from /Users/phil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/minitest-5.16.1/lib/minitest/test.rb:236:in `with_info_handler'
	from /Users/phil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/minitest-5.16.1/lib/minitest/test.rb:93:in `run'
```

This error seems to interfere with test reporting. Moving back to 5.15.0 works fine.

~~For the line where we see the error
(https://github.com/minitest/minitest/blob/v5.16.1/lib/minitest/test.rb#L225):~~
```
Marshal.dump ne                           # can raise TypeError
```

~~Would it make sense to allow this to continue on gracefully if `Marshal.dump` raises a TypeError?~~ Nevermind, looks like that's already the fallback!

**Comment by irphilli** [comment]
I will see if I can get a reproducible case. To add more info, in one of the cases I have locally it's triggered by a `Selenium::WebDriver::Error::ElementClickInterceptedError`.

The backtrace does seem to be causing the issue, looking something like:

```
["0   chromedriver                        0x000000010b534079 chromedriver + 4444281",
 "1   chromedriver                        0x000000010b4c0403 chromedriver + 3970051",
 "2   chromedriver                        0x000000010b15b038 chromedriver + 409656",
 "3   chromedriver                        0x000000010b1989e5 chromedriver + 661989",
 "4   chromedriver                        0x000000010b196593 chromedriver + 652691",
 "5   chromedriver                        0x000000010b193c24 chromedriver + 642084",
 "6   chromedriver                        0x000000010b192885 chromedriver + 637061",
 "7   chromedriver                        0x000000010b1866a9 chromedriver + 587433",
 "8   chromedriver                        0x000000010b1ae792 chromedriver + 751506",
 "9   chromedriver                        0x000000010b185f65 chromedriver + 585573",
 "10  chromedriver                        0x000000010b1ae89e chromedriver + 751774",
 "11  chromedriver                        0x000000010b1c1221 chromedriver + 827937",
 "12  chromedriver                        0x000000010b1ae683 chromedriver + 751235",
 "13  chromedriver                        0x000000010b184a45 chromedriver + 580165",
 "14  chromedriver                        0x000000010b185a95 chromedriver + 584341",
 "15  chromedriver                        0x000000010b50555d chromedriver + 4253021",
 "16  chromedriver                        0x000000010b50a3a1 chromedriver + 4273057",
 "17  chromedriver                        0x000000010b50f16f chromedriver + 4292975",
 "18  chromedriver                        0x000000010b50adea chromedriver + 4275690",
 "19  chromedriver                        0x000000010b4e454f chromedriver + 4117839",
 "20  chromedriver                        0x000000010b524ed8 chromedriver + 4382424",
 "21  chromedriver                        0x000000010b52505f chromedriver + 4382815",
 "22  chromedriver                        0x000000010b53b8d5 chromedriver + 4475093",
 "23  libsystem_pthread.dylib             0x00007ff81d52f4e1 _pthread_start + 125",
 "24  libsystem_pthread.dylib             0x00007ff81d52af6b thread_start + 15",
 "/Users/phil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.2.1/lib/selenium/webdriver/remote/response.rb:56:in `assert_ok'",
 "/Users/phil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.2.1/lib/selenium/webdriver/remote/response.rb:35:in `initialize'",
 "/Users/phil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.2.1/lib/selenium/webdriver/remote/http/common.rb:83:in `new'",
```

**Comment by irphilli** [comment]
So, narrowed this down to the gem `better_errors` being the culprit. It seems is the one adding the binding instance into the backtrace. Example:

```
require "better_errors"

msg = "boom"
bt = [
  "0   chromedriver                        0x00000001068ed079 chromedriver + 4444281",
  "1   chromedriver                        0x0000000106879403 chromedriver + 3970051",
  "2   chromedriver                        0x0000000106514038 chromedriver + 409656"
]
ne = RuntimeError.new msg
ne.set_backtrace bt
p Marshal.dump ne
```

I think this can be closed. (Unless, you want to add a bit more hardening to the exception neutering).

Thanks for taking a look!

**Comment by zenspider** [comment]
This ain't going away... I'd like to try to get your repro working locally and see if I can't clear that up

**Comment by zenspider** [comment]
Nope. I don't have a repro with the code immediately above... are you sure there isn't something more to do? Or maybe more gems interacting?

**Comment by zenspider** [comment]
I've installed binding_of_caller and rails and required rails/railtie to try to get ALL the stuff lumped in... nothing so far.

**Comment by zenspider** [comment]
I need versions of dependencies... and a repro I can get running locally

**Comment by zenspider** [comment]
FFS... I don't actually know what changed, but I have it under test now

**Comment by zenspider** [comment]
```
#>>> ne.method(:set_backtrace).source_location
# => ["/Users/ryan/.gem/repos/minitest/gems/better_errors-2.9.1/lib/better_errors/exception_extension.rb",
```

**Comment by zenspider** [comment]
I believe this to be taken care of

**Comment by zenspider** [comment]
This is released in 5.16.2. Thanks for reporting!

**Comment by zenspider** [comment]
Actually... reopening... please verify on your side and close if you're good. I replicated with better_error but my test might not be comprehensive enough.

**Comment by irphilli** [comment]
It works! 🎉
