### ISSUE TITLE
wrong number of arguments (given 2, expected 1) (ArgumentError) using Mock with delegator

### ISSUE THREAD

**Issue by ThibautGrx** [minitest/minitest#932]
I've upgraded minitest to the latest version (5.16.3) with ruby 2.6.6. and some tests using mock are failling.
It seems related to the feature  "Extended Mock#method_missing to take kwargs"

```ruby
delegator = Object.new
mock = Minitest::Mock.new(delegator)
delegator.nil?
=> false
 mock.nil?
Traceback (most recent call last):
	22: from /home/thibaut/.rbenv/versions/2.6.6/bin/irb:25:in `<main>'
	21: from /home/thibaut/.rbenv/versions/2.6.6/bin/irb:25:in `load'
	20: from /home/thibaut/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/irb-1.3.7/exe/irb:11:in `<top (required)>'
	 3: from (irb):13:in `<main>'
	 2: from /home/thibaut/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/minitest-5.16.3/lib/minitest/mock.rb:153:in `method_missing'
	 1: from /home/thibaut/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/minitest-5.16.3/lib/minitest/mock.rb:153:in `public_send'
/home/thibaut/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/minitest-5.16.3/lib/minitest/mock.rb:153:in `nil?': wrong number of arguments (given 1, expected 0) (ArgumentError)
```
Am I missing something ? thanks

**Comment by blowmage** [comment]
Hi @ThibautGrx, can you try pinning your minitest dependency to https://github.com/blowmage/minitest/tree/fix/mock-delegator-kwargs and see if that fixes this for you?

**Comment by ThibautGrx** [comment]
Hi @blowmage, yes it does

**Comment by zenspider** [comment]
then I assume the latest release fixes you up? Please close if so
