### ISSUE TITLE
TypeError (no implicit conversion of nil into Integer)

### ISSUE THREAD

**Issue by ShaunaMyers** [minitest/minitest#940]
Hey, we're getting this error when running Minitest with ruby 2.7.7. Our quick fix was to remove `srand Minitest.seed` and replace with simply `srand`. Let us know if there is a better solution. Thank you.

```
TypeError: no implicit conversion of nil into Integer
  .../.rbenv/versions/2.7.7/lib/ruby/gems/2.7.0/gems/minitest-5.16.3/lib/minitest/test.rb:70:in `srand'
  .../.rbenv/versions/2.7.7/lib/ruby/gems/2.7.0/gems/minitest-5.16.3/lib/minitest/test.rb:70:in `runnable_methods'
  .../.rbenv/versions/2.7.7/lib/ruby/gems/2.7.0/gems/m-1.5.1/lib/m/runners/minitest_5.rb:15:in `test_methods'
  .../.rbenv/versions/2.7.7/lib/ruby/gems/2.7.0/gems/m-1.5.1/lib/m/executor.rb:90:in `block in suites'
  .../.rbenv/versions/2.7.7/lib/ruby/gems/2.7.0/gems/m-1.5.1/lib/m/executor.rb:88:in `each'
  .../.rbenv/versions/2.7.7/lib/ruby/gems/2.7.0/gems/m-1.5.1/lib/m/executor.rb:88:in `each_with_object'
  .../.rbenv/versions/2.7.7/lib/ruby/gems/2.7.0/gems/m-1.5.1/lib/m/executor.rb:88:in `suites'
  .../.rbenv/versions/2.7.7/lib/ruby/gems/2.7.0/gems/m-1.5.1/lib/m/executor.rb:61:in `tests'
  .../.rbenv/versions/2.7.7/lib/ruby/gems/2.7.0/gems/m-1.5.1/lib/m/executor.rb:15:in `execute'
  .../.rbenv/versions/2.7.7/lib/ruby/gems/2.7.0/gems/m-1.5.1/lib/m/runner.rb:17:in `run'
  .../.rbenv/versions/2.7.7/lib/ruby/gems/2.7.0/gems/m-1.5.1/lib/m.rb:13:in `run'
  .../.rbenv/versions/2.7.7/lib/ruby/gems/2.7.0/gems/m-1.5.1/bin/m:4:in `<top (required)>'
  .../.rbenv/versions/2.7.7/bin/m:23:in `load'
  .../.rbenv/versions/2.7.7/bin/m:23:in `<top (required)>'
```

**Comment by zenspider** [comment]
Bump `m` gem to 1.6+
