### ISSUE TITLE
`-n /reg exp/` not working for me

### ISSUE THREAD

**Issue by abatko** [minitest/minitest#954]
The `-n /regexp/` form of executing tests is not working for me:

```
bundle exec rails test test/integration/my_cool_test.rb -n /user registration/

kernel_require.rb:32:in `require': cannot load such file -- /Users/me/lalala/registration (LoadError)
```

...whereas the underscored form is working:
```
bundle exec rails test test/integration/my_cool_test.rb -n test_caregiver_registration
```

I am using `minitest (5.18.0)` and `rails (6.1.7)`.

**Comment by zenspider** [comment]
```
9979 % ruby -e 'pp ARGV' bundle exec rails test test/integration/my_cool_test.rb -n /user registration/
["bundle",
 "exec",
 "rails",
 "test",
 "test/integration/my_cool_test.rb",
 "-n",
 "/user",
 "registration/"]
```

**Comment by zenspider** [comment]
```
9981 % ruby -e 'pp ARGV' bundle exec rails test test/integration/my_cool_test.rb -n /user.registration/
["bundle",
 "exec",
 "rails",
 "test",
 "test/integration/my_cool_test.rb",
 "-n",
 "/user.registration/"]
```

**Comment by abatko** [comment]
I tried those ideas, and got it to work when substituting the space in the name with `.`.

Both of these work:
```
bundle exec rails test test/integration/flow_test.rb -n /caregiver.registration/
bundle exec rails test test/integration/flow_test.rb -n "/caregiver.registration/"
```

LoadError:
```
bundle exec rails test test/integration/my_cool_test.rb -n /caregiver registration/ 
```

No tests run:
```
bundle exec rails test test/integration/flow_test.rb -n "/caregiver registration/"

0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

So, is that the way?... replace spaces in test names with dots (aka _any char_ reg exp)?

**Comment by zenspider** [comment]
you're removing too much output... minitest shows you what arguments it processes in the test output.

> So, is that the way?... replace spaces in test names with dots (aka any char reg exp)?

no. it is _a_ way, but isn't _the_ way. If quoting + spaces isn't working, that's not minitest. Try removing `bundle exec rails test` and use plain ruby to run:
```
ruby test/integration/flow_test.rb -n "/caregiver registration/"
```

**Comment by zenspider** [comment]
no response in a week. closing

**Comment by abatko** [comment]
I only removed the output because as far as I could tell, there was nothing else in it that hinted at the problem...

Without double-quotes (but still using a space):
```
bundle exec rails test test/integration/flow_test.rb -n /caregiver registration/ 
/Users/meme/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require': cannot load such file -- /Users/meme/Projects/myorg/myrepo/test/integration/flow_test.rb (LoadError)
        from /Users/meme/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/meme/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-6.1.7/lib/rails/test_unit/runner.rb:50:in `block in load_tests'
        from /Users/meme/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-6.1.7/lib/rails/test_unit/runner.rb:50:in `each'
        from /Users/meme/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-6.1.7/lib/rails/test_unit/runner.rb:50:in `load_tests'
        from /Users/meme/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-6.1.7/lib/rails/test_unit/runner.rb:39:in `run'
        from /Users/meme/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-6.1.7/lib/rails/commands/test/test_command.rb:33:in `perform'
        from /Users/meme/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /Users/meme/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/meme/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /Users/meme/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-6.1.7/lib/rails/command/base.rb:69:in `perform'
        from /Users/meme/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-6.1.7/lib/rails/command.rb:48:in `invoke'
        from /Users/meme/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/railties-6.1.7/lib/rails/commands.rb:18:in `<main>'
        from /Users/meme/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/meme/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from bin/rails:4:in `<main>'
```

With double-quotes (but still using a space):
```
bundle exec rails test test/integration/flow_test.rb -n "/caregiver registration/"
Seeding data from file: common
- Creating Riddle Network
- Creating riddle dummy company
Seeding data from common complete!
Seeding data from file: test
Seeding data from test complete!
Run options: -n "/caregiver registration/" --seed 21482

# Running:


Top 0 slowest tests (0.000000 seconds, 0.0% of total time):

[Minitest::CI] Generating test report in JUnit XML format...


Finished in 0.000777s, 0.0000 runs/s, 0.0000 assertions/s.
0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for Integration Tests to /Users/meme/Projects/myorg/myrepo/coverage. 2593 / 4853 LOC (53.43%) covered.
```

Removing `bundle exec rails test` and use plain ruby to run:
```
ruby test/integration/flow_test.rb -n "/caregiver registration/"
<internal:/Users/meme/.rbenv/versions/3.1.3/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- test_helper (LoadError)
        from <internal:/Users/meme/.rbenv/versions/3.1.3/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from test/integration/flow_test.rb:1:in `<main>'
```
