### ISSUE TITLE
NoMethodError for parallel tests

### ISSUE THREAD

**Issue by pftg** [minitest/minitest#982]
For Minitest 5.21.x I each time getting error: 

```
(drbunix:/tmp/druby3363.0) /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/minitest-5.21.2/lib/minitest.rb:965:in `location': undefined method `sub' for nil:NilClass (NoMethodError)
	from (drbunix:/tmp/druby3363.0) /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/minitest-5.21.2/lib/minitest.rb:539:in `location'
	from (drbunix:/tmp/druby3363.0) /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/minitest-5.21.2/lib/minitest.rb:618:in `block in to_s'
	from (drbunix:/tmp/druby3363.0) /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/minitest-5.21.2/lib/minitest.rb:617:in `map'
	from (drbunix:/tmp/druby3363.0) /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/minitest-5.21.2/lib/minitest.rb:617:in `to_s'
	from (drbunix:/tmp/druby3363.0) /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3/lib/rails/test_unit/reporter.rb:23:in `puts'
	from (drbunix:/tmp/druby3363.0) /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3/lib/rails/test_unit/reporter.rb:23:in `record'
	from (drbunix:/tmp/druby3363.0) /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/minitest-5.21.2/lib/minitest.rb:939:in `block in record'
	from (drbunix:/tmp/druby3363.0) /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/minitest-5.21.2/lib/minitest.rb:938:in `each'
	from (drbunix:/tmp/druby3363.0) /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/minitest-5.21.2/lib/minitest.rb:938:in `record'
	from (drbunix:/tmp/druby3363.0) /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3/lib/active_support/testing/parallelization/server.rb:24:in `block in record'
	from (drbunix:/tmp/druby3363.0) /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/minitest-5.21.2/lib/minitest.rb:669:in `synchronize'
	from (drbunix:/tmp/druby3363.0) /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/minitest-5.21.2/lib/minitest.rb:669:in `synchronize'
	from (drbunix:/tmp/druby3363.0) /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3/lib/active_support/testing/parallelization/server.rb:23:in `record'
	from (drbunix:/tmp/druby3363.0) /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/drb-2.2.0/lib/drb/drb.rb:1685:in `perform_without_block'
	from (drbunix:/tmp/druby3363.0) /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/drb-2.2.0/lib/drb/drb.rb:16[41](https://github.com/showca-se/showcase/actions/runs/7616152606/job/20742279286#step:10:42):in `perform'
	from (drbunix:/tmp/druby3363.0) /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/drb-2.2.0/lib/drb/drb.rb:1730:in `block (2 levels) in main_loop'
	from (drbunix:/tmp/druby3363.0) /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/drb-2.2.0/lib/drb/drb.rb:1726:in `loop'
	from (drbunix:/tmp/druby3363.0) /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/drb-2.2.0/lib/drb/drb.rb:1726:in `block in main_loop'
	from /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3/lib/active_support/testing/parallelization/worker.rb:60:in `safe_record'
	from /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3/lib/active_support/testing/parallelization/worker.rb:[53](https://github.com/showca-se/showcase/actions/runs/7616152606/job/20742279286#step:10:54):in `perform_job'
	from /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3/lib/active_support/testing/parallelization/worker.rb:38:in `work_from_queue'
	from /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3/lib/active_support/testing/parallelization/worker.rb:27:in `block in start'
	from /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3/lib/active_support/testing/parallelization/worker.rb:15:in `fork'
	from /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3/lib/active_support/testing/parallelization/worker.rb:15:in `start'
	from /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3/lib/active_support/testing/parallelization.rb:37:in `block in start'
	from /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3/lib/active_support/testing/parallelization.rb:36:in `times'
	from /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3/lib/active_support/testing/parallelization.rb:36:in `each'
	from /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3/lib/active_support/testing/parallelization.rb:36:in `map'
	from /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3/lib/active_support/testing/parallelization.rb:36:in `start'
	from /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/activesupport-7.1.3/lib/active_support/testing/parallelize_executor.rb:19:in `start'
	from /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/minitest-5.21.2/lib/minitest.rb:1[59](https://github.com/showca-se/showcase/actions/runs/7616152606/job/20742279286#step:10:60):in `run'
	from /home/runner/work/showcase/showcase/vendor/bundle/ruby/3.2.0/gems/minitest-5.21.2/lib/minitest.rb:86:in `block in autorun'
```

It could be possible because of a custom backtrace override in one of the lib:s

```
              error = ::Minitest::Assertion.new(error_msg)
              error.set_backtrace(caller(2))
              raise error
```

**Comment by zenspider** [comment]
OK. This is "fixed"... I suspect the above has existed for quite some time but my old version of #location would return "" showing no location.

Release shortly.
